"""agent checkpoints and session context usage

Revision ID: 2c2aaa995b86
Revises: 3e6c51a8538f
Create Date: 2026-09-03 12:27:33.990935

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = '2c2aaa995b86'
down_revision: str | None = '3e6c51a8538f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_checkpoints',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('task_id', models.base.GUID(), nullable=True),
    sa.Column('agent_session_id', models.base.GUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('discoveries', sa.JSON(), nullable=False),
    sa.Column('important_files', sa.JSON(), nullable=False),
    sa.Column('unfinished_work', sa.JSON(), nullable=False),
    sa.Column('blockers', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('test_status', sa.String(length=50), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_sessions', sa.Column('approx_chars', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'approx_chars')
    op.drop_table('agent_checkpoints')
    # ### end Alembic commands ###
