"""initial schema

Revision ID: 2cbbb804f650
Revises: 
Create Date: 2026-09-03 11:34:19.622321

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = '2cbbb804f650'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'QUEUED', 'WORKING', 'BLOCKED', name='agentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_task_id', models.base.GUID(), nullable=True),
    sa.Column('current_agent_session_id', models.base.GUID(), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('repository_path', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('agent_mcp_permissions',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('mcp_server_name', sa.String(length=120), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'mcp_server_name')
    )
    op.create_table('agent_skill_assignments',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('skill_id', models.base.GUID(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'skill_id')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'IN_PROGRESS', 'BLOCKED', 'DONE', name='taskstatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority', native_enum=False, length=10), nullable=False),
    sa.Column('assignee_id', models.base.GUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_requests',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('task_id', models.base.GUID(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('allow_custom_answer', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', 'CANCELLED', name='decisionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_merges',
    sa.Column('task_id', models.base.GUID(), nullable=False),
    sa.Column('type', sa.Enum('DIRECT', 'PR', name='mergetype', native_enum=False, length=10), nullable=False),
    sa.Column('target_branch', sa.String(length=200), nullable=False),
    sa.Column('merge_commit', sa.String(length=64), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('pr_status', sa.Enum('OPEN', 'MERGED', 'CLOSED', name='prstatus', native_enum=False, length=10), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('task_worktrees',
    sa.Column('task_id', models.base.GUID(), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('base_branch', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='worktreestatus', native_enum=False, length=10), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('agent_sessions',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('task_worktree_id', models.base.GUID(), nullable=False),
    sa.Column('claude_session_id', sa.String(length=100), nullable=True),
    sa.Column('cwd', sa.String(length=500), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_worktree_id'], ['task_worktrees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attention_events',
    sa.Column('type', sa.Enum('DECISION_REQUIRED', 'PERMISSION_REQUIRED', 'AGENT_BLOCKED', 'TASK_FAILED', 'AGENT_QUESTION', name='attentiontype', native_enum=False, length=30), nullable=False),
    sa.Column('agent_id', models.base.GUID(), nullable=True),
    sa.Column('task_id', models.base.GUID(), nullable=True),
    sa.Column('decision_request_id', models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_runs',
    sa.Column('agent_session_id', models.base.GUID(), nullable=False),
    sa.Column('bound_via', sa.Enum('SPAWN', 'RESUME', 'MANUAL', name='boundvia', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'KILLED', name='runstatus', native_enum=False, length=10), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('before_head_commit', sa.String(length=64), nullable=True),
    sa.Column('after_head_commit', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_runs')
    op.drop_table('attention_events')
    op.drop_table('agent_sessions')
    op.drop_table('task_worktrees')
    op.drop_table('task_merges')
    op.drop_table('decision_requests')
    op.drop_table('tasks')
    op.drop_table('agent_skill_assignments')
    op.drop_table('agent_mcp_permissions')
    op.drop_table('skills')
    op.drop_table('agents')
    # ### end Alembic commands ###
