"""memory records

Revision ID: 3e6c51a8538f
Revises: c2d8526e272e
Create Date: 2026-09-03 12:09:30.953268

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = '3e6c51a8538f'
down_revision: str | None = 'c2d8526e272e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_records',
    sa.Column('scope', sa.Enum('WORKSPACE', 'AGENT', 'TASK', name='memoryscope', native_enum=False, length=10), nullable=False),
    sa.Column('agent_id', models.base.GUID(), nullable=True),
    sa.Column('task_id', models.base.GUID(), nullable=True),
    sa.Column('type', sa.Enum('FACT', 'DECISION', 'PREFERENCE', 'LESSON', 'TASK_SUMMARY', 'PROJECT_CONTEXT', 'CONVENTION', 'ARCHITECTURE', name='memorytype', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'ARCHIVED', name='memorystatus', native_enum=False), nullable=False),
    sa.Column('superseded_by', models.base.GUID(), nullable=True),
    sa.Column('source_type', sa.Enum('HUMAN', 'AGENT', 'MEETING', 'TASK', 'SYSTEM', name='memorysourcetype', native_enum=False, length=10), nullable=True),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(scope != 'workspace' OR agent_id IS NULL) AND (scope != 'agent' OR agent_id IS NOT NULL) AND (scope != 'task' OR task_id IS NOT NULL)", name='ck_memory_records_scope_owner'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['memory_records.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_records_agent_scope', 'memory_records', ['agent_id', 'scope', 'status'], unique=False)
    op.create_index('ix_memory_records_scope_status', 'memory_records', ['scope', 'status'], unique=False)
    op.create_index('ix_memory_records_task_scope', 'memory_records', ['task_id', 'scope', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_records_task_scope', table_name='memory_records')
    op.drop_index('ix_memory_records_scope_status', table_name='memory_records')
    op.drop_index('ix_memory_records_agent_scope', table_name='memory_records')
    op.drop_table('memory_records')
    # ### end Alembic commands ###
