"""b3 last event at

Revision ID: 4ed9e7ad970e
Revises: c2c434acad1b
Create Date: 2026-09-04 04:46:31.640129

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4ed9e7ad970e'
down_revision: str | None = 'c2c434acad1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_runs', sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_runs', 'last_event_at')
    # ### end Alembic commands ###
