"""a2 a3 memory embeddings and proposals

Revision ID: 4f59a5156114
Revises: 4ed9e7ad970e
Create Date: 2026-09-04 04:58:20.700508

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = '4f59a5156114'
down_revision: str | None = '4ed9e7ad970e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_proposals',
    sa.Column('old_memory_id', models.base.GUID(), nullable=False),
    sa.Column('new_memory_id', models.base.GUID(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'DISMISSED', name='memoryproposalstatus', native_enum=False, length=10), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['new_memory_id'], ['memory_records.id'], ),
    sa.ForeignKeyConstraint(['old_memory_id'], ['memory_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_records') as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('embedding_dim', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_records') as batch_op:
        batch_op.drop_column('embedding_dim')
        batch_op.drop_column('embedding_model')
        batch_op.drop_column('embedding')
    op.drop_table('memory_proposals')
    # ### end Alembic commands ###
