"""phase0 run supervision

Revision ID: 6143eb7ebad6
Revises: cac95b9cd00f
Create Date: 2026-09-04 04:37:37.789588

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6143eb7ebad6'
down_revision: str | None = 'cac95b9cd00f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RUN_STATUS_ENUM = sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'KILLED', 'INTERRUPTED', name='runstatus', native_enum=False, length=20)
RUN_STATUS_ENUM_OLD = sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'KILLED', name='runstatus', native_enum=False, length=10)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_runs') as batch_op:
        batch_op.add_column(sa.Column('kill_requested', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('stdout_offset', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('status', existing_type=RUN_STATUS_ENUM_OLD, type_=RUN_STATUS_ENUM, existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_runs') as batch_op:
        batch_op.alter_column('status', existing_type=RUN_STATUS_ENUM, type_=RUN_STATUS_ENUM_OLD, existing_nullable=False)
        batch_op.drop_column('stdout_offset')
        batch_op.drop_column('kill_requested')
    # ### end Alembic commands ###
