"""c3 meeting turns and session parent

Revision ID: b8e1003773eb
Revises: 4f59a5156114
Create Date: 2026-09-04 05:11:28.800004

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = 'b8e1003773eb'
down_revision: str | None = '4f59a5156114'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_turns',
    sa.Column('meeting_id', models.base.GUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('speaker_id', models.base.GUID(), nullable=False),
    sa.Column('state', sa.Enum('PROMPTED', 'STREAMED', 'COMMITTED', name='meetingturnstate', native_enum=False, length=10), nullable=False),
    sa.Column('run_id', models.base.GUID(), nullable=True),
    sa.Column('message_id', models.base.GUID(), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['meeting_messages.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_turns_meeting_id'), 'meeting_turns', ['meeting_id'], unique=False)

    with op.batch_alter_table('agent_sessions') as batch_op:
        batch_op.add_column(sa.Column('meeting_id', models.base.GUID(), nullable=True))
        batch_op.alter_column('task_worktree_id', existing_type=sa.CHAR(length=36), nullable=True)
        batch_op.create_unique_constraint('uq_agent_sessions_meeting_agent', ['meeting_id', 'agent_id'])
        batch_op.create_foreign_key('fk_agent_sessions_meeting_id_meetings', 'meetings', ['meeting_id'], ['id'])
        batch_op.create_check_constraint('ck_agent_sessions_exactly_one_parent', '(task_worktree_id IS NULL) != (meeting_id IS NULL)')

    with op.batch_alter_table('meeting_messages') as batch_op:
        batch_op.add_column(sa.Column('author', sa.Enum('HUMAN', 'AGENT', 'LEGACY_HUMAN_AS_AGENT', name='meetingauthor', native_enum=False, length=30), server_default=sa.text("'LEGACY_HUMAN_AS_AGENT'"), nullable=False))
        batch_op.alter_column('agent_id', existing_type=sa.CHAR(length=36), nullable=True)

    with op.batch_alter_table('meeting_participants') as batch_op:
        batch_op.add_column(sa.Column('round_robin_position', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('meetings') as batch_op:
        batch_op.add_column(sa.Column('facilitator_instructions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_rounds', sa.Integer(), server_default=sa.text('3'), nullable=False))
        batch_op.add_column(sa.Column('chair_agent_id', models.base.GUID(), nullable=True))
        batch_op.add_column(sa.Column('current_round', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('next_speaker_id', models.base.GUID(), nullable=True))
        batch_op.add_column(sa.Column('loop_state', sa.Enum('IDLE', 'RUNNING', 'PAUSED', name='meetingloopstate', native_enum=False, length=10), server_default=sa.text("'IDLE'"), nullable=False))
        batch_op.create_foreign_key('fk_meetings_chair_agent_id_agents', 'agents', ['chair_agent_id'], ['id'])
        batch_op.create_foreign_key('fk_meetings_next_speaker_id_agents', 'agents', ['next_speaker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings') as batch_op:
        batch_op.drop_constraint('fk_meetings_next_speaker_id_agents', type_='foreignkey')
        batch_op.drop_constraint('fk_meetings_chair_agent_id_agents', type_='foreignkey')
        batch_op.drop_column('loop_state')
        batch_op.drop_column('next_speaker_id')
        batch_op.drop_column('current_round')
        batch_op.drop_column('chair_agent_id')
        batch_op.drop_column('max_rounds')
        batch_op.drop_column('facilitator_instructions')

    with op.batch_alter_table('meeting_participants') as batch_op:
        batch_op.drop_column('round_robin_position')

    with op.batch_alter_table('meeting_messages') as batch_op:
        batch_op.alter_column('agent_id', existing_type=sa.CHAR(length=36), nullable=False)
        batch_op.drop_column('author')

    with op.batch_alter_table('agent_sessions') as batch_op:
        batch_op.drop_constraint('ck_agent_sessions_exactly_one_parent', type_='check')
        batch_op.drop_constraint('fk_agent_sessions_meeting_id_meetings', type_='foreignkey')
        batch_op.drop_constraint('uq_agent_sessions_meeting_agent', type_='unique')
        batch_op.alter_column('task_worktree_id', existing_type=sa.CHAR(length=36), nullable=False)
        batch_op.drop_column('meeting_id')

    op.drop_index(op.f('ix_meeting_turns_meeting_id'), table_name='meeting_turns')
    op.drop_table('meeting_turns')
    # ### end Alembic commands ###
