"""b2 resume intent

Revision ID: c2c434acad1b
Revises: 6143eb7ebad6
Create Date: 2026-09-04 04:44:49.228573

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = 'c2c434acad1b'
down_revision: str | None = '6143eb7ebad6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions') as batch_op:
        batch_op.add_column(sa.Column('resume_pending', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('resume_prompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resume_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('resume_claimed_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('decision_requests') as batch_op:
        batch_op.add_column(sa.Column('agent_session_id', models.base.GUID(), nullable=True))
        batch_op.create_foreign_key('fk_decision_requests_agent_session_id_agent_sessions', 'agent_sessions', ['agent_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_requests') as batch_op:
        batch_op.drop_constraint('fk_decision_requests_agent_session_id_agent_sessions', type_='foreignkey')
        batch_op.drop_column('agent_session_id')
    with op.batch_alter_table('agent_sessions') as batch_op:
        batch_op.drop_column('resume_claimed_at')
        batch_op.drop_column('resume_attempts')
        batch_op.drop_column('resume_prompt')
        batch_op.drop_column('resume_pending')
    # ### end Alembic commands ###
