"""skill catalog and mcp permissions

Revision ID: c2d8526e272e
Revises: 0cd3699964ba
Create Date: 2026-09-03 11:42:38.484752

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = 'c2d8526e272e'
down_revision: str | None = '0cd3699964ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('repository_path', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('agent_mcp_permissions',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('mcp_server_name', sa.String(length=120), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'mcp_server_name')
    )
    op.create_table('agent_skill_assignments',
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('skill_id', models.base.GUID(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'skill_id')
    )
    op.create_index(op.f('ix_agent_skill_assignments_skill_id'), 'agent_skill_assignments', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_skill_assignments_skill_id'), table_name='agent_skill_assignments')
    op.drop_table('agent_skill_assignments')
    op.drop_table('agent_mcp_permissions')
    op.drop_table('skills')
    # ### end Alembic commands ###
