"""rooms and meetings

Revision ID: cac95b9cd00f
Revises: 2c2aaa995b86
Create Date: 2026-09-04 00:16:21.585821

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import models.base

revision: str = 'cac95b9cd00f'
down_revision: str | None = '2c2aaa995b86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('MAIN', 'MEETING', name='roomtype', native_enum=False, length=10), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('room_id', models.base.GUID(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='meetingstatus', native_enum=False, length=10), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('unresolved_questions', sa.JSON(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_table('meeting_messages',
    sa.Column('meeting_id', models.base.GUID(), nullable=False),
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_messages_meeting_id'), 'meeting_messages', ['meeting_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', models.base.GUID(), nullable=False),
    sa.Column('agent_id', models.base.GUID(), nullable=False),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'agent_id', name='uq_meeting_participants_meeting_agent')
    )
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    with op.batch_alter_table('agents') as batch_op:
        batch_op.add_column(sa.Column('room_id', models.base.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agents_room_id'), ['room_id'], unique=False)
        batch_op.create_foreign_key('fk_agents_room_id_rooms', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents') as batch_op:
        batch_op.drop_constraint('fk_agents_room_id_rooms', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agents_room_id'))
        batch_op.drop_column('room_id')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_messages_meeting_id'), table_name='meeting_messages')
    op.drop_table('meeting_messages')
    op.drop_table('meetings')
    op.drop_table('rooms')
    # ### end Alembic commands ###
